# fly.toml app configuration file generated for test-case-generator-app on 2025-10-01T08:36:29+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-case-generator-app'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
