app = "test-case-generator-app"
primary_region = "syd"

[build]
  builder = "paketobuildpacks/builder-jammy-base"

[env]
  NODE_ENV = "production"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 1
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024
